:dls_url:       https://demo.digital.library.illinois.edu
:medusa_url:    https://demo.medusa.library.illinois.edu
host: demo.medusahq.library.illinois.edu
shibboleth:
  host: demo.medusahq.library.illinois.edu
  request_type: header
  uid_field: eppn
  extra_fields:
    - eppn
