:dls_url:       https://digital.library.illinois.edu
:medusa_url:    https://medusa.library.illinois.edu
host: medusahq.library.illinois.edu
shibboleth:
  host: medusahq.library.illinois.edu
  request_type: header
  uid_field: eppn
  extra_fields:
    - eppn
